### PR TITLE
prevent service subscribers overwriting already known service definitions

### LINKED ISSUE #193: Intermittant issue where service container type is thought to be the autowireable interface/alias, not concrete type.
Hi there!

We some code in a test that looks like this:
```php
    $session = $container->get('session');
    $flashBag = $session->getFlashBag();
```

The session service is defined [here](https://github.com/symfony/symfony/blob/6a7273f3e226f27bb82dfc6466542ae637576648/src/Symfony/Bundle/FrameworkBundle/Resources/config/session.php#L35-L46).

For the most part, this works fine, but **sometimes**, this code errors as follows:

```
ERROR: UndefinedMethod - TransactionTest.php:91:31 - Method Symfony\Component\HttpFoundation\Session\SessionInterface::getFlashBag does not exist (see https://psalm.dev/022)
        $flashBag = $session->getFlashBag();
```

I am guessing that, most of the time, the type is resolved to [Session](https://github.com/symfony/symfony/blob/5.2/src/Symfony/Component/HttpFoundation/Session/Session.php), but then sometimes it resolves to the alias [SessionInterface](https://github.com/symfony/symfony/blob/5.2/src/Symfony/Component/HttpFoundation/Session/SessionInterface.php), and the error shows.

I'm trying to dig and debug to see what I can find, but any pointers would be great.

Thanks

### PR DESCRIPTION
**Pull request by bendavies**
This is my attempt and fixing #193.

Service subscribers are overwriting services already known via the containerXml.
I believe this to be a bug.

Note the acceptance test, and that psalm knows that the type is the concrete `Symfony\Component\HttpKernel\HttpKernel`

Comments welcome!

Thanks

### CODE REVIEW

File: src/Handler/ContainerHandler.php [hunk 1]
```diff
@@ -188,9 +188,11 @@ private static function addSubscribedServicesArray(Expr\Array_ $array, Codebase
                 $key = $arrayItem->key;
                 $serviceId = $key instanceof String_ ? $key->value : $className;
 
-                $service = new Service($serviceId, $className);
-                $service->setIsPublic(true);
-                self::$containerMeta->add($service);
+                if (null === self::$containerMeta->get($className)) {
```
Comment (seferov) [inline src/Handler/ContainerHandler.php:191]: @bendavies thank you for the contribution. I think here, this condition can be a temporary solution. ContainerMeta and Service classes should be improved to make them work with aliases better. Here in this case, http_kernel -> HttpKernelInterface -> should resolve to HttpKernel as service.

Comment (bendavies) [reply src/Handler/ContainerHandler.php:191]: unsure what you mean, but `http_kernel` does resolve to `HttpKernel` in this case. see the acceptance yest

**Comment by bendavies** [comment]
thanks @seferov for the merge!

File: src/Handler/ContainerHandler.php (hunk 1 above)
Comment (seferov) [reply src/Handler/ContainerHandler.php:191]: @bendavies 

> unsure what you mean, but http_kernel does resolve to HttpKernel in this case

yes, it does because it is defined in xml file as `http_kernel`. If the name was different it wouldn't.

Lets take a little different example for better explanation:

```php
public static function getSubscribedServices(): array
{
    return [
        'http_kernel_with_a_different_name' => HttpKernelInterface::class,
    ];
}
```

In this case, this is not going to resolved with this new changes. Because `if` check is done by class name and new alias for the service is not going to be added to the container but it should. Thus it will result in service not found error.

The correct solution IMHO is to change service class to allow add more than one aliases (with visibility, public false or true) and add such cases with aliases. And on ContainerMeta class adding new service should check if it resolves to the actual class if interface is provided.
